MIN_AREA = 3
MAX_AREA = 100000

MIN_POPULATION = 200
MAX_POPULATION = 1000000

FILES = {
    "1lKAvoPMYCid4AtNq3ZRzxef-TdSoJTKX" : "isl_4326.gpkg",
    "1ayojeFO69awJuZsB7oRrAwd5DpLrNEgI" : "continents.gpkg",
    "1b7Vv0JmzfqWrp-zzoly1foBdAGRynMjm": "geothermal_potential.gpkg",
    "1cnPzc1fy_gaTVS9_Rn8_njC-AzztJv8G" : "PVOUT-year.tif" ,
    "1ieyOvUeqGKecSXrAyeglvZNT4JFbBReG" : "population.tif" ,
    "19fjhD2KyChnA218ZqOQ1DXSMLDiIFwcr" : "PVOUT_01.tif" ,
    "1qZw9f0ILBZwfyC_l9tTvFoYcxlOHqJ0U" : "PVOUT_02.tif" ,
    "1VCLMtNMjrixYFY2N6k2hY7SV9cOCiW_0" : "PVOUT_03.tif" ,
    "14JNi90pdq6O2c4qHjdVjFOLpVF9iLB0M" : "PVOUT_04.tif" ,
    "1HLqn5ikewQQgfzNMRk6EqTNl7NvZtLyk" : "PVOUT_05.tif" ,
    "1fFrkH9CEmoQVHYFAeItEVAuQOucpZoHV" : "PVOUT_06.tif" ,
    "10VC49V2BBbG6HO_TmyznYLBjIPNTpRAO" : "PVOUT_07.tif" ,
    "1bI-v5lfzMWnAljNTsDrNgUOMDMLeUX8f" : "PVOUT_08.tif" ,
    "1sv2ONDEOsWZeynXoh-ISvn8IEVrTAb07" : "PVOUT_09.tif" ,
    "1qsgUlsm59KkYEHF7TsxG6uTS238pbaow" : "PVOUT_10.tif" ,
    "1GTE2H6kvDdvoyWFfkp_w9k6kSQabsXEb" : "PVOUT_11.tif" ,
    "1ohBmGbiNdufaF_iB4NzUN45F4Vad3RZq" : "PVOUT_12.tif" ,
    "1Ce3a25PpPx-riLMh42axtTzvVZkpCUR_" : "EC2019.tif",
    "1UKec_gnsHnhGbo3xoLP3ncesw2V86B83" : "2019GDP.tif",
    "1oEDpwVb3dAGTlHuzooXkSuUWWVQYBY3A" : "hydro.gpkg",
    "1ZUEKfhvKRuxEF3TmUEfDpkABSr30tsJs" : ["eap","FixedFoundation.cpg"],
    "1VM9i1Zjnbe0xgEX0yzFpfzD5-XhWX2lk" : ["eap","FixedFoundation.dbf"],
    "1kUC4yWy4qSdieXD8taYDm0hCaMLbk8V2" : ["eap","FixedFoundation.prj"],
    "1vcEYjVcwVGHOtAfG5GTDjfnTxkNH_1W5" : ["eap","FixedFoundation.shp"],
    "1s4qCbZoP-fuH7ghgZGhw798aPHd-PBvb" : ["eap","FixedFoundation.shx"],
    "1BrE-NS8ZCHTJZzGHnGCmq0UzNV0wZdep" : ["eap","FloatingFoundation.cpg"],
    "1ztQs-5kbLQOZh9KvC5DcpLHi9Ij6JQ2Z" : ["eap","FloatingFoundation.dbf"],
    "17Gej0_1vE5jtIgsQ6M6v0kZhwpVYDal1" : ["eap","FloatingFoundation.prj"],
    "1QgCaHXOSlGr92XSni4KNV4BDvnaLx6s7" : ["eap","FloatingFoundation.shp"],
    "14AyvEZt-9r9vm5B1zBnhOG6nrKSjyErk" : ["eap","FloatingFoundation.shx"],
    "1OWpw87YT43a9Hzk1ErukvKYZf7G3Yej7" : ["eca","FixedFoundation.cpg"],
    "1fHJN-FkndGF83p-_y8dYSXqse2aW5jXn" : ["eca","FixedFoundation.dbf"],
    "1Npw6A7Y59L3Wf8aIz3FANwtiOfVTPk0Y" : ["eca","FixedFoundation.prj"],
    "17q-YlbfSNGB8uLJaSJvoNP3_TgozMwGP" : ["eca","FixedFoundation.shp"],
    "1gxrsKnq94sNcnuoKe-TpMkDxMfAFMszp" : ["eca","FixedFoundation.shx"],
    "1AxJ0NxLG2heCESpNeIQ3ArQY3RtgyeAh" : ["eca","FloatingFoundation.cpg"],
    "1EwA9CmkZmq2ajfdBgRTZ2ZulUWrlI2m2" : ["eca","FloatingFoundation.dbf"],
    "19ndZ1Y2on5r-_NTMfyFcvn5hZwW735gG" : ["eca","FloatingFoundation.prj"],
    "1gDar_w2caB1NyEin7tIqvOCvdX7affzP" : ["eca","FloatingFoundation.shp"],
    "1MwpDW3R_OPb9wkiGj1b1rcPsgID-7WIk" : ["eca","FloatingFoundation.shx"],
    "1k3LXdQ085ksFk65ff9AAfDXX5LbrwKfx" : ["lac","FixedFoundation.cpg"],
    "1FxpVSXmAZLFr0lW0mtr3F0vziLShcfxf" : ["lac","FixedFoundation.dbf"],
    "17G5_ErjepB9KJIUWc3095zSXGp4F0FK7" : ["lac","FixedFoundation.prj"],
    "1FFXmLp5mSgat5VxQaQmLeRNFybt8r9LW" : ["lac","FixedFoundation.shp"],
    "1d9xDfUeqDJnWmTBahEkuHVx8MzQVvHYZ" : ["lac","FixedFoundation.shx"],
    "1dQhFa2FeX04PWGUD67pK1_5CGsqL-u1H" : ["lac","FloatingFoundation.cpg"],
    "1Ghu3qWMYkt9ZmrIBiw2DUB9mbbP90TTD" : ["lac","FloatingFoundation.dbf"],
    "1H8F73G9pQka8mE3JH4BUXsRdVdFD1ZwQ" : ["lac","FloatingFoundation.prj"],
    "1zbX_Caxk_sEUw-zdtDR8QeoCavUlUY0I" : ["lac","FloatingFoundation.shp"],
    "1TcLAoP3hv8xqWdIRDRzum2mwJV9N0DA6" : ["lac","FloatingFoundation.shx"],
    "16A8Ipw_daJLq2ZNhAagZJSqLS8zZRcsc" : ["mena","FixedFoundation.cpg"],
    "1RcEO1bcP9xvS0NfTAYlsuMZsBQY4MU7f" : ["mena","FixedFoundation.dbf"],
    "18zRiLE0Jdwy0X6UKYtw4V8OHTLEn4csV" : ["mena","FixedFoundation.prj"],
    "15IVAib5A9mmyWOgRGNxWlhco0DE-UURT" : ["mena","FixedFoundation.shp"],
    "17TbnIw_ulUuhjbvbtrdSOEGQKr2aFR56" : ["mena","FixedFoundation.shx"],
    "17HKV3tYjUX49FF-aVd-JvgFi4XZQxjZc" : ["mena","FloatingFoundation.cpg"],
    "1Y8yKg0KWCizKBLOai5aDHZ0LGkmecua1" : ["mena","FloatingFoundation.dbf"],
    "12LnRQk0E9uQJuDBemOlkG6kBUavBb5xe" : ["mena","FloatingFoundation.prj"],
    "1WiY5-u3xEKsO2QrT81uTkm9WpEBiPorL" : ["mena","FloatingFoundation.shp"],
    "1iMKDqA6hw7al74uzCGy7TXLFGtupidoX" : ["mena","FloatingFoundation.shx"],
    "1sMNuvDKmAKN9CZn2pGUppM1aatnECZ2f" : ["na","FixedFoundation.cpg"],
    "1lEp2axpaWYKUgR7-J5TgIcr-0PHkljwJ" : ["na","FixedFoundation.dbf"],
    "1E5ZFS2nhF4CRehQspX8ycXVktdnRJnTY" : ["na","FixedFoundation.prj"],
    "1H-5bsKXFKfMeotstgK9KR6TaNFOLhqKQ" : ["na","FixedFoundation.shp"],
    "1JM9Qg-lxShgWLLyPX7qFIwubYPG664WY" : ["na","FixedFoundation.shx"],
    "1qaRXioWfOE-hciKFwjNXhFkH7tL81spA" : ["na","FloatingFoundation.cpg"],
    "1V7cSMnnClHvMf6VGMHYhE9VTmSlen9ol" : ["na","FloatingFoundation.dbf"],
    "1pxqgfRNMDO3Kp5cNUO8GE3Ec96PzhRA3" : ["na","FloatingFoundation.sbn"],
    "1bgexMF6cw6NxNXV6ZCb86FZiitQAgeRA" : ["na","FloatingFoundation.sbx"],
    "18cXhjqxXLd4k-woPHVSBE8zmwAMTEp2Z" : ["na","FloatingFoundation.shp"],
    "1U7VLFnErNlmuE61AMRylrwa59Pg6Hs8S" : ["na","FloatingFoundation.shx"],
    "1ItZRhs8aoJQ2JJQKyJifUkaC18urbFJy" : ["sa","FixedFoundation.cpg"],
    "1bhEr7eBXMLfciSca-yvldDlZNmFX8XDJ" : ["sa","FixedFoundation.dbf"],
    "1W1AyGShzIEB8paRG2t_jKiDpY6Emi9X6" : ["sa","FixedFoundation.prj"],
    "1sndDws__mbO8njj9ju7l7Wpwuec9pgLY" : ["sa","FixedFoundation.shp"],
    "1c0s0Lc2g1T_rjDf-0O_cca_kVYzWtdh_" : ["sa","FixedFoundation.shx"],
    "15W_xTTl6Ttie0RgrLnda4TUsM0nkDjL9" : ["sa","FloatingFoundation.cpg"],
    "1XnRWf6KJC6c3Tx9DBAyK42QlJYe1muTi" : ["sa","FloatingFoundation.dbf"],
    "1jRIGUHgrO24PJSXifJ8pjOwZTcLe1V54" : ["sa","FloatingFoundation.prj"],
    "1NBZqVbxPPIkFBA9bRdv3mrnctjyREe9P" : ["sa","FloatingFoundation.shp"],
    "1TJNa3DDQc9fpnIxZrYpieVDPV8I75xGC" : ["sa","FloatingFoundation.shx"],
    "1G2lPhP_RuiEWP_MAiG4AoQjTHxMS23mA" : ["ssa","FixedFoundation.cpg"],
    "1S7DTxJY-ZbRYf2K7LVh2Jl4f5hLli2bb" : ["ssa","FixedFoundation.dbf"],
    "1pf-lxN7lpwbGusJ6ypqSBnL-nma6Tr-s" : ["ssa","FixedFoundation.prj"],
    "1n2SLYLwbuERMdP-O7BqS2IGiMxwakGve" : ["ssa","FixedFoundation.shp"],
    "1vVoh3vipBfNEbCyJQt1NfdmV-5PZ4lgx" : ["ssa","FixedFoundation.shx"],
    "16Twd6h2PggevuprzKy-1B9qRto_-Erhb" : ["ssa","FloatingFoundation.cpg"],
    "1H3EYe2FzX4f1cVP9fL-4NFziibqgWB_B" : ["ssa","FloatingFoundation.dbf"],
    "1VdsAiMJAiwV2bLF9k6Y5bztcM-8vzIE1" : ["ssa","FloatingFoundation.prj"],
    "1lXmc_wInAwg5q9cXvitwrp6OuauY6w7x" : ["ssa","FloatingFoundation.shp"],
    "1o3NjE0W1ZrTayf_cg-PW_a_SyoWnINND" : ["ssa","FloatingFoundation.shx"]
}

proj='ee-giorgioramundo99'